language: php

php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --prefer-source --dev
  - php app/console assetic:dump --env=prod --no-debug

script:
  - ./bin/phpunit
  - ./bin/behat
  - ./bin/phpspec run
  - ./bin/phpmd src/ text phpmd.xml --exclude 'DependencyInjection/Configuration.php,DependencyInjection/*Extension.php'
  - ./bin/phpmd app/ text phpmd.xml --exclude 'cache/prod/,SymfonyRequirements.php,AppKernel.php'
  - ./bin/phpcs --standard=phpcs.xml src/ -n
  - ./bin/phpcs --standard=phpcs.xml app/ -n
